version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - cache_data:/data
    ports:
      - 6379:6379
    networks:
      - network
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning

volumes:
  cache_data:

networks:
  network:
